services:
  - type: web
    name: biva-imobiliaria
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: biva-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: RENDER_EXTERNAL_URL
        sync: false

databases:
  - name: biva-db
    databaseName: biva
    user: biva
    plan: free
